### ISSUE TITLE
Why did I train the data it  got a 'keyError'

### ISSUE THREAD

**Issue by Delta0406** [ahmdtaha/knowledge_evolution#1]
![image](https://user-images.githubusercontent.com/51943093/113563576-821adc00-963a-11eb-8a6f-168afb7654a4.png)
Hi, I used your method then got a error like the picture. Could you give you .csv file, thanks a lot

**Comment by ahmdtaha** [comment]
I don't think you read the usage example.

> The Flower102Pytorch loader (`data>flower.py`) works directly with this [Flower102 dataset](https://drive.google.com/file/d/1ftEUxDIS_VOcx_OO70QDfZvHNDxXXgRY/view?usp=sharing). This is the original flower102, but with an extra `list` directory that contains csv files for trn, val and tst splits. Feel free to download the flower dataset from [oxford website](https://www.robots.ox.ac.uk/~vgg/data/flowers/102/), just update `data>flower.py` accordingly.
