### ISSUE TITLE
retrain fit-hypothesis

### ISSUE THREAD

**Issue by kwk12306** [ahmdtaha/knowledge_evolution#8]
Thank you for your exciting work!
I've got a few questions after reading your paper, hoping you could help answer:
 when I use a small split-rate, After g generations, if  the  fit hypothesis‘ test acc is too much  lower than dense network  N，can we retrain split_model  to  approach N？is it significant？In other words, can fit hypothesis be trained from scratch without specific hardware and computing library support？

**Comment by ahmdtaha** [comment]
Thanks for your interest. I am happy to answer your question but I am not sure I understand it correctly

can fit hypothesis be trained from scratch without specific hardware and computing library support？
> Yes, I believe I tried something similar here [1]. Check question no.3 (Fig 1).

when I use a small split-rate, After g generations, if the fit hypothesis‘ test acc is too much lower than dense network N，can we retrain split_model to approach N？is it significant？
> If the split-rate is too small, the fit-hypothesis won't achieve similar performance to the dense network N. I am not sure what do you mean by "can we retrain split_model to approach N?"

[1] https://ahmdtaha.github.io/paper/KE_FAQ.pdf
